### ISSUE TITLE
Incorrect documentation for error handling

### ISSUE THREAD

**Issue by vfr292** [recurly/recurly-client-python#104]
HI,

In the handling errors section of https://docs.recurly.com/client-libraries/python it reads:

<code>
except ValidationError, errors:<br>
    for e in errors.itervalues():
</code>

Which raises an error that errors has no itervalues.

I think it should read:

<code>
except recurly.ValidationError, vadlidation_error:<br>
    for e in vadlidation_error.errors.itervalues():
</code>

Sorry about the weird line breaks :(  I couldn't get it to look nice...

~Victor

**Comment by austinheap** [comment]
Hi @vfr292, thanks for reporting the issue. We're looking into it internally.

**Comment by austinheap** [comment]
Hi @vfr292, we've updated the documentation. Please let me know if there's anything else we can help with!
