### ISSUE TITLE
Please create a tag and release for 2.2.9

### ISSUE THREAD

**Issue by netrounds-fredrik** [recurly/recurly-client-python#109]
There is a commit (https://github.com/recurly/recurly-client-python/commit/3fd47d7fd0bd1d766c880ce63f69a0e40f81d2a6) but no tag and nothing on the releases page (https://github.com/recurly/recurly-client-python/releases)

**Comment by drewish** [comment]
@cbarton did you forget to `push --tags`? ;)

**Comment by drewish** [comment]
@netrounds-fredrik thanks for letting us know. https://github.com/recurly/recurly-client-python/releases/tag/2.2.9 is up now.
