### ISSUE TITLE
Transaction object has incorrect attributes list

### ISSUE THREAD

**Issue by muzhig** [recurly/recurly-client-python#130]
According to data in webhooks we're receiving from recurly, transaction object has 'id' rather than 'uuid' field. And our biggest problem- missing subscription_id field, which is present in hook data, but there is no such attribute on transaction object. I can confirm, that this simple one-liner solves the issue for us.

```
Transaction.attributes += ('id', 'subscription_id')
```

although I'm not sure other fields in list are correct.

**Comment by bhelx** [comment]
Hey @muzhig

There isn't a direct way to get the subscription_id off the transaction as far as I know. If the transaction comes from a susbcription, you should be able to do this:

```python
transaction.subscription().uuid
```

But that fetches the susbscription first. You could also reach into the transaction and pull the url out then parse out the uuid.

**Comment by bhelx** [comment]
It seems like in the webhooks, `Transaction` is the only model that uses `id`. The rest correctly use `uuid`. I'm looking into it why.
