### ISSUE TITLE
account.billing_info raises AttributeError on new accounts.

### ISSUE THREAD

**Issue by Eleeleth** [recurly/recurly-client-python#145]
Repeat of #98, but I'm having this occur in 2.2.17. I should note I'm on python 3.5.0, just in case.

Using the example in the docs for creating a new account, and then a new billing info object:

```py
account = Account(account_code='1')
account.email = 'verena@example.com'
account.first_name = 'Verena'
account.last_name = 'Example'
account.save()

# account.billing_info here raises AttributeError, 
# so I copy-paste the example code exactly, including the get.

account = Account.get('1')
billing_info = account.billing_info #  but this still raises an AttributeError!
billing_info.token_id = 'TOKEN_ID'
billing_info.save()
```

I seem to have been able to resolve this by calling `account.update_billing_info` with a new BillingInfo object I create and add the token to, like so:

```py
account = Account.get('1')
billing_info = BillingInfo()
billing_info.token_id = 'TOKEN_ID'
account.update_billing_info(billing_info)
```

Before I arrived to the solution above, I also tried attaching the billing info object I created to the account and saving it, but that raised an unrelated AttributeError, so I didn't continue down that path. 

While I have a solution that works for me as-is, I'm curious as to whether this is intended to be used this way, or if I'm going against the grain, since the example differed from my implementation. 

Thanks for your time!

**Comment by bhelx** [comment]
@Eleeleth It seems to me like the correct way to do it is the way you described in the second code example. That's the way I'd expect a python user to create a billing info object. The error is because a new account doesn't have a billing info object yet. The docs look more like what you would want to do if you are updating the billing info object rather than creating one.

I think maybe I'll just update the docs. Let me think about the best way to deal with it.

**Comment by Eleeleth** [comment]
Thanks for the response! I'm glad to know that my solution is in-line with what is expected, and that soothes any fear that it may have been an internal api. +1 for just updating the docs, although that's merely from a user perspective.

**Comment by marians** [comment]
My +1 for updating the docs. I also ran into this, which cost me time and impaired my trust in Recurly's ability to provide a functioning API. And while at it, please add

```python
import recurly
from recurly import Account, BillingInfo
```

at the very top of the Python examples.

**Comment by bhelx** [comment]
@Eleeleth @marians I've updated the documentation to reflect this.

@marians I have a project coming up to audit and improve all the example code in the docs and I'll definitely add the explicit imports back in. It's my hope that all the examples can be independently runnable. It seems many of them have gotten stale and I apologize that it's reflected poorly on us. In the meantime feel free to post any questions or more good suggestions as issues on this repo.

**Comment by marians** [comment]
Thanks for updating the docs!

Side node: After I found that I would need to import quite a number of classes from `recurly`, I decided to only `import recurly` in my code and then refer to the classes using their full name. Following the Python rule "Explicit is better than implicit".

```python
import recurly
account = recurly.Account(...)
```

**Comment by bhelx** [comment]
@marians Yes, this is typically how I do it as well. I like keeping the classes in their own namespace. There is also this Zen rule:

```
python -m  this | grep Namespaces
Namespaces are one honking great idea -- let's do more of those!
```
