### ISSUE TITLE
Errors unprintable in python 3.5.0 / client 2.2.17

### ISSUE THREAD

**Issue by Eleeleth** [recurly/recurly-client-python#146]
When I get a traceback from the recurly client, what I see is this:

```
recurly.errors.ValidationError: <unprintable ValidationError object>
```

Digging further, it seems to be caused by a nested exception, thrown in the `__unicode__`/`__str__` methods:

```
 File "<snip>/lib/python3.5/site-packages/recurly/errors.py", line 53, in __str__
    return self.__unicode__()
  File "<snip>/lib/python3.5/site-packages/recurly/errors.py", line 184, in __unicode__
    return six.u('; ').join(six.text_type(error) for error in self.errors.itervalues())
AttributeError: 'dict' object has no attribute 'itervalues'
```

This is probably a python 3.X issue, as `itervalues()` was removed in favor of `values()`.

**Comment by bhelx** [comment]
Closed with https://github.com/recurly/recurly-client-python/pull/147
