### ISSUE TITLE
BillingInfo with token id raising exception (with recurly.js)

### ISSUE THREAD

**Issue by jinto** [recurly/recurly-client-python#155]
I think, the code in https://docs.recurly.com/js/?python#using-a-token must be changed. 
```
subscription = recurly.Subscription(
    plan_code = request.POST['plan'],
    account = recurly.Account(
        account_code = 'usercode',
        billing_info = recurly.BillingInfo(token_id = request.POST['recurly-token'])
    )
)
subscription.account.billing_info.blacklist_attributes = ('currency')
subscription.save()
```

**Comment by bhelx** [comment]
Hey @jinto, thanks for reporting.

This is a bug that is actually being fixed right now on the server side. I will ping back when it's fixed. In the mean time, could you please post the error you are getting for searchability?

**Comment by jaykwonpark** [comment]
Thanks for your comment.
The message is below.
`billing_info_invalid: no other attributes are allowed when a token is provided`

**Comment by jinto** [comment]
Thanks for your comment.
The message is below.
`billing_info_invalid: no other attributes are allowed when a token is provided`

**Comment by bhelx** [comment]
Thanks @jinto 

Sorry this was overlooked in the release of this new feature. The expected release date for the server fix is Wednesday. Will reply back here when I can confirm it's fixed.

**Comment by bhelx** [comment]
Hey @jinto

The server side fix for this should now be live. I'm going to close the issue. Please re-open if you are still having the problem.
