### ISSUE TITLE
Webhook and invoice

### ISSUE THREAD

**Issue by jinto** [recurly/recurly-client-python#156]
Hi, I'm implementing webhook listner, for "closed_invoice_notification"

```
data = recurly.objects_for_push_notification(request.body.decode())
print(data['type'])
print(data['account'])
print(data['invoice'])
```

works well. but i need to know the subscription_id. In notification xml there is `subscription_id`.
Is there any way to get the subscription related to this invoice?
thanks.

**Comment by bhelx** [comment]
You'd have to fetch the invoice with the invoice uuid then get the subscription from the invoice.

**Comment by bhelx** [comment]
Sorry, I misread this the first time. You should be able to just fetch the subscription given the id. Something like this:

```php
try {
  $subscription = Recurly_Subscription::get(data['invoice']['subscription_id']);
  print "Subscription: $subscription";
} catch (Recurly_NotFoundError $e) {
  print "Subscription Not Found: $e";
}
```

Is this what you mean?

**Comment by jaykwonpark** [comment]
Hi, sorry for late answer.

There is no 'subscription_id' in 'invoice' on closed_invoice_notification.

fields of invoice are : 'uuid', 'state', 'invoice_number', 'invoice_number_prefix', 'po_number', 'vat_number', 'subtotal_in_cents', 'tax_in_cents', 'tax_type', 'tax_rate', 'total_in_cents', 'currency', 'created_at', 'updated_at', 'line_items', 'transactions', 'terms_and_conditions', 'customer_notes', 'address', 'closed_at', 'collection_method', 'net_terms'.

**Comment by aaron-suarez** [comment]
Hi there @jinto and @jaykwonpark! You may be aware of the new webhooks related to the new Credit Invoices feature. If not, you can read all about it [here](https://docs.recurly.com/docs/credit-invoices-release).

The TL;DR is that the new webhooks for [Charge Invoices](https://dev.recurly.com/page/webhooks#charge-invoice-notifications) and [Credit Invoices](https://dev.recurly.com/page/webhooks#charge-invoice-notifications) do include a `subscription_ids` array of related subscriptions.

If you haven't already enabled your site for Credit Invoices, it will be automatically enabled for you on November 1st.

For that reason, I'm going to go ahead and close out this issue. If you have any problems getting the subscription_id using the new Credit Invoice webhooks, please feel free to reopen this issue or open a new issue regarding that.

Thank you very much for your feedback!
