### ISSUE TITLE
Need API Access to Notes Field in Manual Payment

### ISSUE THREAD

**Issue by johncronin3** [recurly/recurly-client-python#172]
![image](https://cloud.githubusercontent.com/assets/1261668/16314215/d6cc02c6-394a-11e6-95f4-bd24b96fb2d7.png)

**Comment by bhelx** [comment]
This should map to 'description' on the Adjustment. Let me know if that doesn't work for you.

https://github.com/recurly/recurly-client-python/blob/master/recurly/__init__.py#L584

**Comment by johncronin3** [comment]
The description seems to only store or return 48 characters.
