### ISSUE TITLE
What key to use for Recurly.js.PRIVATE_KEY

### ISSUE THREAD

**Issue by logston** [recurly/recurly-client-python#196]
I see there is a variable for `API_KEY` (`recurly.API_KEY`). I can find that key here: https://15five.recurly.com/developer/api_keys

I also see a variable for a `PRIVATE_KEY` (`recurly.js.PRIVATE_KEY`). However, I can not find where to get that key within Recurly. Where do I find this key?

Also, looking through the code, it appears that `PRIVATE_KEY` is only used in `recurly.js.sign` and `recurly.js.sign` is not used anywhere. Is this key necessary anymore?

**Comment by bhelx** [comment]
@logston See the section of the docs `Configuration`

https://github.com/recurly/recurly-client-python#configuration

```
import recurly

recurly.SUBDOMAIN = 'your-subdomain'
recurly.API_KEY = '012345678901234567890123456789ab'

# Optionally set a certificate authority certs file to validate Recurly's certificate
recurly.CA_CERTS_FILE = '/etc/pki/tls/certs/ca-bundle.crt'

# Set a default currency for your API requests
recurly.DEFAULT_CURRENCY = 'USD'
```

**Comment by bhelx** [comment]
@logston Also, you should know that you don't need that `PRIVATE_KEY` because it's for an older version of recurly.js.

**Comment by silambarasanmkce** [comment]
> @logston Also, you should know that you don't need that `PRIVATE_KEY` because it's for an older version of recurly.js. It's there for backwards compatibility.

any alternate for this 
recurly.js.private_key

**Comment by aaron-suarez** [comment]
@silambarasanmkce The private key is no longer necessary in modern versions of RecurlyJS. Please check the docs here https://dev.recurly.com/docs/recurlyjs

The Python client only needs the `token_id` returned by RecurlyJS to create a billing info on an account. That specific documentation is here https://dev.recurly.com/docs/create-an-accounts-billing-info-token

If you have more questions, please feel free to reach out to support https://support.recurly.com/hc/en-us
