### ISSUE TITLE
Subscription.save() bug

### ISSUE THREAD

**Issue by Thalmann** [recurly/recurly-client-python#199]
If you have a subscription with a pending quantity change for instance:

quantity: 1
pending_quantity: 3

If you get that subscription and then save it:
subscription.save()

It will override the pending quantity so we will just have:

quantity: 1
And no pending changes.

**Comment by bhelx** [comment]
Hey @Thalmann 

I've tried reproducing this:

```python
sub = recurly.Subscription.get('3b6aa62f4bac3e177ebefc421fbef29c')
sub.quantity = 3
sub.save()
```

It seems to send across the new quantity and the subscription is changed. Could you paste some example code demonstrating the problem from your end? Also, can you enable debugging and paste the debug logs:

```python
# To enable debugging
import logging
logging.basicConfig(level=logging.INFO)
logging.getLogger('recurly').setLevel(logging.DEBUG)
```

**Comment by Thalmann** [comment]
Hey @bhelx ,
Pretty simple:

`
s = Subscription.get('3c7d434282d05556d01d324b1ab90627')

s.timeframe = 'renewal'

s.quantity = 4

s.save()

s.save()
`

This overwrites the pending subscription

**Comment by bhelx** [comment]
@Thalmann 

Ah I see. So you have a change that is set to take effect at renewal. Calling save again sends this xml:

```xml
<subscription><timeframe>now</timeframe></subscription>
```

And overwrites the change. I'm not sure if this is a bug exactly, but I can see how it would be confusing. Is there another way you'd expect it to behave? Are you trying to add things to the pending Subscription?

**Comment by Thalmann** [comment]
@bhelx 

I expect that the pending subscription stays as it is else we need something like this:

s = Subscription.get('3c7d434282d05556d01d324b1ab90627')
s.quantity = 2
s.pending_subscription.quantity = 4
s.save()

Can you see what i mean?

**Comment by bhelx** [comment]
No I'm sorry I don't follow. Is it your intent to change the quantity to 2 now and have it change to 4 at renewal? In which case I think the code would be something like this:

```python
s = Subscription.get('3c7d434282d05556d01d324b1ab90627')
s.timeframe = 'now'
s.quantity = 2
s.save()
s.timeframe = 'renewal'
s.quantity = 4
s.save()
```

**Comment by Thalmann** [comment]
Yes, the problem with that is every time i want to keep the pending subscription i have to send two requests.

**Comment by bhelx** [comment]
This is a limitation of the API. You can only have one pending subscription at a time.

**Comment by Thalmann** [comment]
Yes, i am not asking for more pending subscription.

It is just odd to me that when i save the subscription it overwrites my pending subscription.

**Comment by bhelx** [comment]
Okay I understand now. Since our API currently does not do support this, this is an API feature request. The best way forward is to file an issue with support requesting this feature. If we can't add the feature for you, they can help you figure out a way to do what you are trying to accomplish.
