### ISSUE TITLE
Strings over 48 chars getting truncated

### ISSUE THREAD

**Issue by johncronin3** [recurly/recurly-client-python#203]
See  https://github.com/recurly/recurly-client-python/issues/172#event-822731015

![image](https://cloud.githubusercontent.com/assets/1261668/25777134/fd9b2c14-32a1-11e7-86cd-897eb6adf671.png)

Many more characters were entered into this description.  I verified this is happening with others as well.

**Comment by bhelx** [comment]
Hey @johncronin3, perhaps this can be handled better, either in docs or in code, but this is a limitation applied on the server side.

**Comment by bhelx** [comment]
I'm closing this for now since it's mostly a server side change that's needed. Please re-open if this is causing you pain and we can look at changes to this library to help.
