### ISSUE TITLE
Previewing, changing and then saving a Subscription throws a ConnectionRefusedError

### ISSUE THREAD

**Issue by moritzgloeckl** [recurly/recurly-client-python#207]
Hi,

I have the following code and noticed a bug:

    subscription = recurly.Subscription(
			plan_code = 'pluskey',
			currency = 'EUR',
			quantity = request.form['plan_quantity'],
			account = account
    )
		
    subscription.preview()
    subscription.unit_amount_in_cents = 1200
    subscription.save()

`subscription.save()` then throws 

> ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

I also think to know **why** this happens:

When calling `subscription.preview()` the attribute `subscription._url` gets set (to an empty string), and the `subscription.save()` method checks for it:

    if hasattr(self, '_url'):
        return self._update()
    return self._create()

But `.update()` can't be called because `_url` is empty thus resulting in an `ConnectionRefusedError`. I would suggest either modifying the `.preview()` method to not create the `_url` attribute or changing the `.save()` method to include an additional check like this:

    if hasattr(self, '_url'):
        if self._url:
            return self._update()
    return self._create()

**Comment by moritzgloeckl** [comment]
My current workaround involves deepcopying the subscription because I ran into other problems, mainly that `account `and `billing_information` were missing after calling `.preview()`:

    from copy import deepcopy
    
    oldSubscription = deepcopy(subscription)
    subscription.preview()
    oldSubscription.unit_amount_in_cents = 1200
    oldSubscription.save()

**Comment by bhelx** [comment]
Hey @moritzgloeckl

Thanks for reporting this. I think this is an unfortunate consequence of the design of this library. I will look into it to see if I can fix it on the library level. In the mean time, I think it may be safer to create a new subscription object with your attributes because I'm not sure if there are any consequences with using deepcopy. Something like this:

```python

preview_sub = recurly.Subscription(
		plan_code = 'pluskey',
		currency = 'EUR',
		quantity = request.form['plan_quantity'],
		account = account
)
preview_sub.preview()

subscription = recurly.Subscription(
		plan_code = 'pluskey',
		currency = 'EUR',
		quantity = request.form['plan_quantity'],
		account = account,
                subscription.unit_amount_in_cents = 1200
)
subscription.save()


```

**Comment by aaron-suarez** [comment]
Closing this issue because it would require a redesign of the library.
