### ISSUE TITLE
BadRequestError is not being used as documentation promises it

### ISSUE THREAD

**Issue by pl-jankowskimichal** [recurly/recurly-client-python#209]
So the current definition of BadRequestError is like this:
`class BadRequestError(ClientError):
    """An error showing the request was invalid or could not be
    understood by the server.
    The error was returned as a ``400 Bad Request`` response.
    Resubmitting the request will likely result in the same error.
    """
    pass
`
Please focus on the last sentence., few days ago we got this:
> BadRequestError: connection_error: Tax service currently unavailable, please try again later

I'm not really sure if this is the right place to raise that issue, because basically it seems that it's the Recurly API not returning correct HTTP status (400 instead of 503). Altough I'm pretty sure it will be easier to get to the devs via github then support form :)

**Comment by bhelx** [comment]
@pl-jankowskimichal That's a great point, and one we noted when we last saw this error. I think the API should be returning a 50X error. I'll try to get something worked out for next deploy :)

**Comment by bhelx** [comment]
I'll close this ticket when the API change is deployed.

**Comment by aaron-suarez** [comment]
This change has long since been deployed.

@pl-jankowskimichal If you notice any other similar problems, feel free to open a separate issue. Thanks!
