### ISSUE TITLE
ValidationError.Suberror doesn't have proper python3 stringification

### ISSUE THREAD

**Issue by pakal** [recurly/recurly-client-python#217]
It must have a __str__() forwarding to ___unicode__(), like other classes.

Monkey patching goes like : 

```
good_str_func = recurly.errors.ValidationError.__str__
recurly.errors.ValidationError.Suberror.__str__ = good_str_func
```

**Comment by bhelx** [comment]
Thanks for pointing this out! Can you check that #218 resolves the issue for you?

**Comment by pakal** [comment]
Well it looked OK have, but https://github.com/recurly/recurly-client-python/issues/197 has broken the __str__ of these exceptions too.

**Comment by bhelx** [comment]
I've updated #218 with some of your comments.

**Comment by pakal** [comment]
I added minor remarks on https://github.com/recurly/recurly-client-python/pull/218/files ,  but the behaviour looks good now
