### ISSUE TITLE
Please create GitHub release for 2.6.2

### ISSUE THREAD

**Issue by cederberg** [recurly/recurly-client-python#220]
Seems v2.6.2 is tagged and available via pip install, but no GitHub release has been made. Old version still marked as "latest".

**Comment by bhelx** [comment]
You can find the release here:
https://github.com/recurly/recurly-client-python/releases/tag/2.6.2
I'm going to update the release notes today and I will make sure it's marked as latest.

**Comment by bhelx** [comment]
I've updated the notes on the releases. Please let me know if there are any further questions.
