### ISSUE TITLE
Recurly Transaction call sporadically hangs

### ISSUE THREAD

**Issue by saillsha** [recurly/recurly-client-python#223]
I have a cron job that does ETL work on recurly data everyday. As part of the script, I call  ```recurly.Transaction.all(sort = 'updated_at', begin_time = YESTERDAY)```

The script occasionally hangs at this point when running in a dev environment using the recurly sandbox key. I'm not sure where in the recurly client it is hanging or what's causing it.

**Comment by bhelx** [comment]
Could we get some more information on this? How long does it hang for? Does it throw an error, or maybe it hangs for a long time then resolves, or maybe it hangs and never completes?

**Comment by saillsha** [comment]
It hangs indefinitely, without throwing any error. The hard part about the bug is it occurs sporadically, and only in our dev environment.

**Comment by bhelx** [comment]
That may be a hard thing to debug from the context of this library. It sounds more like a networking issue. Have you tried contacting Recurly support? They may be able to help you diagnose it. Also, keep in mind you can set a timeout so it won't hang indefinitely.

```python
recurly.SOCKET_TIMEOUT_SECONDS = 10 # seconds
```

**Comment by saillsha** [comment]
okay I will try that, thank you.
