### ISSUE TITLE
New webhook attribute addition breaking Python webhook parsing

### ISSUE THREAD

**Issue by niekbaeten** [recurly/recurly-client-python#228]
Yesterday the following part was added to your `new_dunning_event_notification` webhook:
```xml
<subscription_ids type="array">
  <subscription_id>
    <subscription_id>abcdefg</subscription_id>
  </subscription_id>
</subscription_ids>
```

We are using version 2.3.1 of your library and it fails to parse the webhook now with the following exception:
```python
File "/usr/local/lib/python2.7/dist-packages/recurly/__init__.py", line 1046, in objects_for_push_notification
  res = Resource.value_for_element(child_el)
File "/usr/local/lib/python2.7/dist-packages/recurly/resource.py", line 404, in value_for_element
  return [cls._subclass_for_nodename(sub_elem.tag).from_element(sub_elem) for sub_elem in elem]
File "/usr/local/lib/python2.7/dist-packages/recurly/resource.py", line 364, in _subclass_for_nodename
    % nodename)
ValueError: Could not determine resource class for array member with tag 'subscription_id'
```

**Comment by bhelx** [comment]
@niekbaeten This was supposed to be a non-breaking change but it appears to be breaking the python library. We've identified the problem and have a fix coming server side. I'll keep this open until we can confirm it's working. Sorry for the trouble.

**Comment by jinto** [comment]
I got the same error. +1 vote.

**Comment by bhelx** [comment]
@niekbaeten @jinto The server-side change should have fixed. Can you confirm you are no longer seeing this error?

**Comment by niekbaeten** [comment]
Yeah I can see working ```new_dunning_event_notification``` now.
Thanks for the fix.

**Comment by bhelx** [comment]
Please re-open if anyone is still having this problem.
