### ISSUE TITLE
getting coupons used on a subscription

### ISSUE THREAD

**Issue by lauxley** [recurly/recurly-client-python#229]
I am not sure if this is a bug from the recurly api or me failing to understand something, I took a subscription with a discount code, in the admin the subscription shows up with the coupon (in the `Coupon Redemptions` row, but when i can't fetch this information through the api.
```
>> uuid = '41b41fcb91851ea4d4f3b74b5b9172ec'
>> r = recurly.Subscription().get(uuid=uuid)
>> r.redemptions()
>> b'<?xml version="1.0" encoding="UTF-8"?>\n<redemptions type="array">\n</redemptions>\n'
>> []
>> r.coupon_code
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-8-431a5a12e662> in <module>()
----> 1 r.coupon_code

/home/robin/Projects/recurly-client-python/recurly/resource.py in __getattr__(self, name)
    582                     return self._make_actionator(url, method)
    583 
--> 584             raise AttributeError(name)
    585 
    586         # Follow links.

AttributeError: coupon_code
```

Corresponding API call
`https://api.recurly.com/v2/subscriptions/41b41fcb91851ea4d4f3b74b5b9172ec/redemptions`
Response
`b'<?xml version="1.0" encoding="UTF-8"?>\n<redemptions type="array">\n</redemptions>\n'`

Am i missing something ?

**Comment by bhelx** [comment]
`coupon_code` is a write-only field on the `Subscription`. It gets applied to the invoice. If you want to get your redemption object, i'd fetch it from the invoice:

```python
uuid = '41b41fcb91851ea4d4f3b74b5b9172ec'
sub = recurly.Subscription.get(uuid)
inv = sub.invoice()
redemptions = inv.redemptions()
print(redemptions)
# => [<recurly.Redemption object at 0x110004390>]
```

Can you tell me what are the details of your coupon?

**Comment by bhelx** [comment]
Also, could you tell me which version of the python client you are using?

**Comment by lauxley** [comment]
I can't rely on invoices because i need this info right after taking the subscription, and the invoice doesn't always exist at this point.
`git+https://github.com/recurly/recurly-client-python.git@c24c2b3f8589fe629e93316f7754aacb825ad6c4` I am not sure why this specific commit, i'm using [django-recurly](https://github.com/pakal/django-recurly/blob/master/requirements.txt).

**Comment by bhelx** [comment]
Can you tell me what the settings of the coupon are from the admin page? From the documentation on `/subsrciptions/<uuid>/redemptions`:

```
Returns an array of active coupon redemptions associated with the specific subscription. Coupon redemptions are only associated with a subscription if the coupon has a discount level of "subscription". Inactive coupon redemptions will not be returned.
```

**Comment by lauxley** [comment]
## Coupon Summary
#### Internal Name
free-trial
#### Code
free-trial
#### Discount
Free Trial: 15 day
#### Duration
Single use
#### Maximum Redemptions
Unlimited
#### Redemptions Per Account
Unlimited
#### Eligible Charges
All plans
#### Discount Level
Subscription 

I tried with a regular percent discount and i have the exact same result, `.redemptions()` returns an empty array.

**Comment by bhelx** [comment]
@lauxley I think the problem is that the `subscription/<uuid>/redemptions` returns only `active` coupon redemptions whereas I believe your redemption should now be `expired` after being used.

If you are still having trouble with it, I'd suggest you reach out to support and let them know what you are trying to accomplish. They can provide you more answers than I can with this matter.

**Comment by lauxley** [comment]
Ok thx, i'll give it a try.
