### ISSUE TITLE
Make "recurly" not a global singleton

### ISSUE THREAD

**Issue by bobbyrullo** [recurly/recurly-client-python#239]
Right now there's not really recurly client object, there's the recurly client library with a bunch of top-level methods.

This makes it very east to configure, but makes it impossible to talk to multiple recurly accounts in the process in a thread-safe way.

**Comment by bhelx** [comment]
I agree that this is a problem but it's a difficult refactor for such an old codebase and we currently do not have plans to take on this work. I am going with the "explicit-client" design in the next iteration of this library.

I'm open to reviewing this work as a PR from someone, but I'm concerned about how hard that may be to verify and test.

**Comment by bobbyrullo** [comment]
@bhelx - sounds reasonable. Any idea of a timeframe for the next iteration of the Python library?
