### ISSUE TITLE
transaction.subscriptions() raises Exception

### ISSUE THREAD

**Issue by jinto** [recurly/recurly-client-python#273]
For some transactions calling subscription() method raises Exception. So caller must wrap the method call with try-catch. How about just return empty collection?

**Comment by aaron-suarez** [comment]
@jinto I took a look at the library and I'm having a bit of trouble finding a method named `subscription` or `subscriptions` on a Transaction object. Can you provide some example code of the scenario you're talking about?

**Comment by aaron-suarez** [comment]
There is a `subscriptions()` method on an `Account`. Let's suppose account "1" has no subscriptions. This script will print out `0` without throwing an exception:

```python
account = recurly.Account.get('1')
subs = account.subscriptions()
print(len(subs)) # prints 0
```

**Comment by aaron-suarez** [comment]
Closing this out due to inactivity and the fact that it cannot be reproduced. Please feel free to re-open with a code snippet that demonstrates the problem.
