### ISSUE TITLE
Add exception class to differentiate server errors that raise UnexpectedStatusError from other status codes

### ISSUE THREAD

**Issue by polishmatt** [recurly/recurly-client-python#276]
At the moment in my application I assume ServerError captures all possible server errors. This is not the case as I've occasionally seen 530s and at any time a new 5xx code could be used. Handling UnexpectedStatusError as well and branching behavior based on status codes is tricky given my application's current structure. It would be much simpler to have a set of exception classes that I can assume are server errors.

I'm proposing:
* A new class UnexpectedServerError that inherits from UnexpectedStatusError (possibly also ServerError) and is used for any unexpected (not in error_classes) status codes in the range 500-599
* A new class UnexpectedClientError that inherits from UnexpectedStatusError (possibly also ClientError) and is used for any unexpected (not in error_classes) status codes in the range 400-499
* Any other status codes still use UnexpectedStatusError as they do now.
* Possibly a dedicated class that inherits from ServerError to handle 530s if someone knows how these are used by the recurly API. I don't have full logs of those errors so I don't know what the full status line is.

**Comment by aaron-suarez** [comment]
I looked into it a little bit and I don't believe that handling 530s separately will be necessary. I fully agree with you on having a way to generalize about handling server errors and client errors differently, even if they're not specifically listed in the `error_classes` dict.

I'm going to go ahead and follow your proposal except without handling 530s specifically. If you encounter a 530 status returned from the Recurly API, I suggest you just retry the request after a certain amount of time passes. If you discover a condition that reliably produces a 530 on every request, please contact Recurly support so we can see if anything can be done on the API side to prevent that error from occurring.
