### ISSUE TITLE
Cannot redeem a coupon

### ISSUE THREAD

**Issue by jbagot** [recurly/recurly-client-python#317]
The method `redeem()` doesn't exist in `Coupon` class. 
How can I redeem a coupon?
Also I checked the tests and in this line the method is called:
https://github.com/recurly/recurly-client-python/blob/967a92a2f866174d204468f04b2865b311caa9fe/tests/test_resources.py#L640

But the test pass because there is a `try, finally`.

**Comment by joannasese** [comment]
Hi @jbagot. 

The redeem method is only present when the coupon is redeemable and single-code (not bulk).

If your coupon meets these requirements, you can verify by looking for the redeem action in the coupon's xml:

`<a name="redeem" href="https://user-name.recurly.com/v2/coupons/user-coupon-name/redeem" method="post"/>\n</coupon>\n'`

**Comment by joannasese** [comment]
@jbagot I'm closing this issue. Please feel free to reopen if the problem persists.
