### ISSUE TITLE
Head count not matching library output

### ISSUE THREAD

**Issue by mayank-bark** [recurly/recurly-client-python#321]
`transaction_list = []

    for transaction in Transaction.all(

    begin_time=datetime(2019,1,3, 6, 0, 0).isoformat(),

    end_time=datetime(2019,1, 3, 7, 0, 0).isoformat(),

    sort='updated_at'):

    transaction_dict = {'uuid' : transaction.uuid,

                        'action': transaction.action,

                        'currency': transaction.currency,

                        'amount_in_cents': transaction.amount_in_cents,

                       'tax_in_cents': transaction.tax_in_cents,

                       'status': transaction.status,

                       'reference': transaction.reference,

                       'test': transaction.test,

                       'voidable': transaction.voidable,

                       'description': transaction.description,

                       'refundable': transaction.refundable,

                       'created_at': transaction.created_at,

                       'updated_at': transaction.updated_at,

                       'gateway_type': transaction.gateway_type,

                       'origin': transaction.origin,

                       'message': transaction.message,

                       'approval_code': transaction.approval_code}

    transaction_list.append(transaction_dict)

    df = pd.DataFrame(transaction_list)`

So I'm running the above code. I pull in Recurly records for a given timeframe, then write them to a pandas DataFrame.

As a sanity check, I check the length of the dataframe against the X-Records listed in the head request for the same time frame. The numbers line up for smaller intervals but once the module is returning 1000+ records the records don't line up.

Is that expected? Am I missing something?

Edit: For the listed timeframe, the head request indicates I should receive 18986 records, while the module only returns 12632. Am I hitting some type of rate limit?

**Comment by bhelx** [comment]
@mayank-bark We can take a look. I think it's more likely that the HEAD call is not applying the filters (and thus overcounting) than the other way around. If you were hitting any kind of rate limit you'd receive an exception. Do you have a clue? If you log the resulting HTTP/XML traffic that would help us narrow it down faster.

**Comment by bhelx** [comment]
> As a sanity check, I check the length of the dataframe against the X-Records listed in the head request for the same time frame. The numbers line up with smaller intervals but once the module is returning 1000+ records the records don't line up.

That's pretty unusual

**Comment by bhelx** [comment]
Another question while I'm thinking about it. Does your dataframe have an index? Can you double check by looking at the count on the `transaction_list` list and not the dataframe? I want to rule out any possible issue with the DataFrame.

**Comment by mayank-bark** [comment]
I ran everything again without the "updated_at" flag, and now it matches perfectly. It seems the head request doesn't filter updated_at correctly

*Note: I checked the length of the `transaction_list` as well, no problems there.

**Comment by bhelx** [comment]
I can't seem to reproduce:

```python
count = 0
for transaction in recurly.Transaction.all(
    per_page=200,
    begin_time=datetime(2016, 9, 10, 0, 0, 0).isoformat(),
    end_time=datetime(2019, 9, 10, 23, 0, 0).isoformat(),
    sort='updated_at'):

    count += 1

print("Pagination count")
print(count)

count = recurly.Transaction.count(
    per_page=200,
    begin_time=datetime(2016, 9, 10, 0, 0, 0).isoformat(),
    end_time=datetime(2019, 9, 10, 23, 0, 0).isoformat(),
    sort='updated_at')

print("HEAD count")
print(count)
```

Both counts come out the same.

But yes, what you are saying suggests maybe there is something going on with the way the server is counting when it receives a `sort` parameter on a HEAD request. In my test site, all of my created_at and updated_at properties are likely the same which might explain why I can't repro. I'm happy to look further into this but I don't think it's related to this library. Would you mind filing an official support case?
