### ISSUE TITLE
Using Transaction Search - Invoice ID 

### ISSUE THREAD

**Issue by mayank-bark** [recurly/recurly-client-python#324]
Hi, when I pull transactions using Recurly's async export, it has invoice ID/ subscription ID as columns. However, when I pull transactions through the API, it does not contain invoice ID/ sub ID. How do I gather that information through the API?

**Comment by bhelx** [comment]
I'm not aware of an id field, is it a large hex string like this? `4e48ab484212a7b4472ab242a398455d`

If so, it probably maps to the `uuid` on the subscription and invoice objects in the V2 API.

**Comment by mayank-bark** [comment]
ah ok. The thing is, invoices:transactions is one to many, whereas transactions:invoice is 1:1. As such, it is much harder to create joinable tables with the current setup. I'll work with what is available though. Feel free to close.

**Comment by bhelx** [comment]
okay closing, but feel free to re-open or keep the convo going.
