### ISSUE TITLE
V3 interface: site id

### ISSUE THREAD

**Issue by everdance** [recurly/recurly-client-python#325]
client initialization only requires API key:
```python
class BaseClient:
    def __init__(self, api_key):
        self.__api_key = api_key
        self.__conn = http.client.HTTPSConnection(HOST, PORT)
```

Checked out locally on some client methods, but found no where to pass site id(sub domain)  for any client methods like:
https://github.com/recurly/recurly-client-python/blob/master/recurly/client.py#L205

Is version 3 ready for use?

**Comment by drewish** [comment]
The subdomain is no longer required, it can be inferred from the API key. Were you getting a specific error?

**Comment by everdance** [comment]
yup, i suspect it couldn't infer the subdomain from the server side, as it returns account not found error:
```
File "recurly_test.py", line 14, in <module>
    main()
  File "recurly_test.py", line 10, in main
    'country': 'US'
  File "/usr/local/lib/python3.7/site-packages/recurly/client.py", line 309, in update_billing_info
    return self._make_request("PUT", path, body, None)
  File "/usr/local/lib/python3.7/site-packages/recurly/base_client.py", line 55, in _make_request
    error,
recurly.errors.NotFoundError: Couldn't find Account with id = 5da43a657a2f2100018be776. Recurly Request Id: 525a32cad947ccc2-EWR
```

```python
import recurly

client = recurly.Client('xxxxxxxxxxxxxxxxxxxxxxxxxxxxx')

def main():
    client.update_billing_info('5da43a657a2f2100018be776', {
        'country': 'US'
    })

if __name__ == "__main__":
    main()
```

**Comment by drewish** [comment]
Ah, it looks like you're trying to fetch the account by its code. In V3 we've changed the default identifier to be the record id rather than code. To do that you'd just need to prefix it with the string `code-`.

**Comment by everdance** [comment]
Gotcha, thank you.

**Comment by bhelx** [comment]
> Is version 3 ready for use?

@everdance V3 is ready and supported. You'll find the first release on pypi as `3.0.0` and here are the docs: https://recurly-client-python.readthedocs.io/en/latest/

Sorry about those confusing errors, it's one of the first things I'm looking at improving.
