### ISSUE TITLE
Where are the 2.9.x docs?

### ISSUE THREAD

**Issue by ericjung** [recurly/recurly-client-python#326]
All of these 404:

https://github.com/recurly/recurly-client-python/tree/2.9.8/docs
https://github.com/recurly/recurly-client-python/tree/2.9.9/docs
https://github.com/recurly/recurly-client-python/tree/2.9.10/docs

Where can I find the docs for 2.9.x ?

**Comment by drewish** [comment]
I'll let someone else chime in on the correct location but where did you find those links? We'd obviously like to update them to avoid sending anyone to a 404.

**Comment by bhelx** [comment]
@ericjung I do not think we've ever had generated docs for the V2 python library.

**Comment by ericjung** [comment]
@bhelx I'm trying to figure out how to get accounting_code on a plan using 2.9.x, after upgrading from a very old version. The object model changed after the upgrade, and I can't find this. Looks like it may be on something called plan.attributes... but without docs or assistance, I'm at a loss. Any advice?

**Comment by bhelx** [comment]
Happy to try to help. As far as I know, `Plan#accounting_code` should still be present. Are you finding it is not? https://github.com/recurly/recurly-client-python/blob/v2/recurly/__init__.py#L1401

If you could share some code, that may help as well.

**Comment by ericjung** [comment]
accounting_code is present but, as far as I know, I cannot access it anymore except by an index into the attributes tuple. In 2.2.x this is how I retrieved it:

```
def isGoogleSubscription(self, message_type, dictFromXml):
  try:
    subscr = recurly.Subscription.get(dictFromXml['subscription_id'])
  except recurly.errors.NotFoundError as e:
    # Can't find a subscription with that UUID. Maybe it's a transaction id
    try:
      t = recurly.Transaction.get(dictFromXml['subscription_id'])
      subscr = t.subscription()
    except recurly.errors.NotFoundError as e:
      # Huh? Can't find it
      self.logger.info("This message is NOT for a google subscription/account.")                                
      return False

  plan = subscr.plan
  if plan.accounting_code != 'goog' and plan.accounting_code != 'google':
    self.logger.info("This message is NOT for a google subscription/account.")
    return False
  ...
  ...
  return True
```

The benefit of `plan.accounting_code` over something like `plan.attributes[15]` (and I dont even know if that's the correct index) should be obvious: if I change Recurly python client library versions, I just have to hope the attribute order is the same? Is `plan.attributes[15]` the proper/only way to get `accounting_code` now?

Thank you for your time!

**Comment by johnnybubonic** [comment]
i did a git bisect and:

```
775cc403383cbeed17b4ec4b3a67329cc7b839f4 is the first bad commit
commit 775cc403383cbeed17b4ec4b3a67329cc7b839f4
Author: Benjamin Eckel <bhelx@simst.im>
Date:   Fri Mar 23 11:50:32 2018 -0500

    API v2.10 Changes

:040000 040000 c63a6c5a8110fdf18b44a8c4a97bcaa4dc9ee7cb 82a78dd6cdd69dc15811ce1deb1864bffc1b80c4 M      recurly
:040000 040000 7d02aff29619a15bb168222f578b6a0c7e84030d 323171ac24acea8984d1409bfd43f4d474cfcc75 M      tests
```
I didn't notice readily what would cause this offhand, but it seems in that commit - whenever `<recurly.Subscription>.plan`/`<recurly.Plan>` ceased being able to be instantiated. `<recurly.Subscription>.plan()` gives `TypeError: 'Plan' object is not callable`. And if one attempts to call `<recurly.Plan>.accounting_code`, they get `AttributeError: accounting_code`.

**Comment by ericjung** [comment]
To add to @johnnybubonic, I think I used to use `subscr.plan()` in 2.2.19 not `subscr.plan`

**Comment by bhelx** [comment]
Here's what I've found so far. The embedded `plan` on the subscription only has 2 elements. if you want the whole plan, you need to fetch it. For example, here's one way:

```python
print(sub.plan) # only has `name` and `plan_code`
plan = recurly.Plan.get(sub.plan.plan_code)
```

I believe in the previous versions, that `plan` was a `relatiator` link which fetched the plan for you. In other words `sub.plan` changed from a function to a an object (when there was an embedded object present).

I wanted to point something else out possibly unrelated, transaction no longer has a one to one relationship with subscription but rather a one to many, you'll now need to get your subscription like so:

```python
sub = transaction.subscriptions()[0]
```

If you aren't already, you might want to consider using the [Python Upgrade Guide](https://dev.recurly.com/page/python-upgrade-guide). We've tried to collect all the breaking change notes in the releases on this page.

Finally, I think you should take a look at V3 of the API and python library: https://recurly-client-python.readthedocs.io/en/latest/

You may fairly consider it too big of a jump, and of course we will continue to support V3. But I think you'll find a simpler maintenance V3 w/ V3.

**Comment by ericjung** [comment]
Thanks, @bhlex. Recurly I'd pushing really hard for us to upgrade to v3.x. it's almost as if they do not care about their customers still using 2.x. Whether true or not, that is the tone of the messaging we are getting.

We have an extensive system written in Python 2.x which has not been ported to 3.x yet and won't be until next year, regardless of the Python 2.x EOL time frame.

How do you propose we use Recurly Python client 3.x with Python 2.x?

Thank you

**Comment by bhelx** [comment]
@ericjung sorry, we don't intend for that to be the messaging. We're just trying to get the word out. Like I said before, we plan to support V2 for years to come and we've finally built a team around the API and clients. The vast majority of our merchants are on V2 and their success is tied to ours.

Having said that, on October 25th, V2 of this library will be 8 years old. There's only so much we can improve while still maintaining backwards compatibility with this library and ecosystem. We felt it necessary to lay a new foundation for the next 8 years.

> We have an extensive system written in Python 2.x which has not been ported to 3.x yet and won't be until next year, regardless of the Python 2.x EOL time frame.

There's no immediate rush. I'm only suggesting you look at V3 as I think it's a better experience (there are actually reference docs as just one example). Everyone's situation is different on upgrading though and you still ultimately need to determine the cost-benefit of different paths forward. Again, I sincerely apologize about the tone. We're excited about this new ecosystem and we're finding it to be a hard line to straddle.

> How do you propose we use Recurly Python client 3.x with Python 2.x?

That is a tricky one. We chose to not support Python 2.7 in V3 because it's EOL is in 2 months. Our  policy on language support is to only support what the language maintainers support. We must do this for security and PCI reasons.

**Comment by ericjung** [comment]
We got it working with your help, @bhelx. Thank you so much.

> we plan to support V2 for years to come

Interesting. I know you have a rolling phase-out plan whereby old versions are completely blocked from recurly servers after a certain period. I wonder when that will be for the las 2.x release (presumably 2.9.10 but I'm not sure if you've abandoned 2.x now or not?)

> Having said that, on October 25th, V2 of this library will be 8 years old. 

Understood. But not all of Recurly customers are 8 years old. To us, it looks like we've been using this API for 3 years (maybe less for others) and are being **heavily persusaded**, not gently encouraged, to upgrade... not too far from *hey, that's a nice business you got there, how'd you like us to cripple it?*

I sincerely hope I am just misinterpreting things at Recurly, but we've had lots of discussions recently because of this upgrade tone. The discussions are *should we rewrite to Recurly v3 or switch to stripe subscriptions instead?* They are just discussions at this point.

> Again, I sincerely apologize about the tone. We're excited about this new ecosystem and we're finding it to be a hard line to straddle.

I appreciate that. But think of this from your customers' perspectives: rewriting subscription management systems adds little or no value to existing, polished legacy systems, and certainly doesn't change revenue, so it hard to sell to management for prioritization. If it gets prioritized because the vendor (Recurly) is threatening blockage of their services, the vendor becomes a liability, not a partner.

> Our policy on language support is to only support what the language maintainers support. We must do this for security and PCI reasons.

I don't believe there are security or PCI compliance reasons surrounding Python 2.7. If there were security or PCI compliance issues with it, people would have left Python 2.x in droves years ago. I genuinely look forward to your reply on this because I'm not an infosec expert.

Again, thank you for your time. Give us time to catch up!

**Comment by bhelx** [comment]
You're welcome! Glad we could help.
