### ISSUE TITLE
cast api response error throws exception

### ISSUE THREAD

**Issue by everdance** [recurly/recurly-client-python#345]
I ran into the following exception stack on api request:
```
Traceback (most recent call last):
File "home/scripts/clean_test.py", line 31, in terminate client.terminate_subscription('uuid-'+uuid, refund='none') 
File "/usr/local/lib/python3.7/site-packages/recurly/client.py", line 2275, 
in terminate_subscription return self._make_request("DELETE", path, None, kwargs) 
File "/usr/local/lib/python3.7/site-packages/recurly/base_client.py", line 45, in _make_request raise Resource.cast_error(resp) 
File "/usr/local/lib/python3.7/site-packages/recurly/resource.py", line 38, in cast_error error.message + ". Recurly Request Id: " + response.request_id, error TypeError: 'NoneType' object is not callable
```
which throws from: 
```python
        klass = locate("recurly.errors.%s" % class_name)
        return klass(
            error.message + ". Recurly Request Id: " + response.request_id, error
        )
```

**Comment by bhelx** [comment]
Hi @everdance,

Thanks for submitting. I cannot seem to reproduce. Can you tell us which version of the library are you using? I think I have an idea what is causing this but I'd like to be able to reproduce first.

**Comment by everdance** [comment]
@bhelx it's from version `v2019-10-10`.  this error only shows up when I ran the script in our cloud environment which get 4xx response from recurly server, but when I ran the script locally with  same lib version and parameters, it does not throw any error. I am quite confused. I suspect the cloud lib version might have a bug in http request.

The cloud version is installed under docker image `python:3.7-alpine`

the main func in my script is:
```python
def terminate(code, uuid):
    try:
        client.terminate_subscription('uuid-'+uuid, refund='none')
        client.deactivate_account('code-'+code)
    except recurly.errors.NotFoundError:
        logging.warning("[%s] not found %s",code, uuid)
    except recurly.errors.BadRequestError:
       logging.warning("[%s] bad request", uuid)
    except recurly.errors.ValidationError as e:
       logging.warning("[%s] validatation error: %s", uuid, e)
    except recurly.errors.InternalServerError as e:
       logging.warning("recurly server error %s", e)
    except recurly.RecurlyError as e:
       logging.warning("recurly error %s", e)
    except Exception as e:
        logging.warning("[%s][%s] unexpected error: %s", code, uuid, e)
        traceback.print_exc(file=sys.stdout)
```

**Comment by bhelx** [comment]
> It's from version v2019-10-10

That's the HTTP API version, do you know which version of the library you are using? Would be b/w `3.0.0` and `3.3.1`. `3.3.1` being the latest release.

> but when I ran the script locally with same lib version and parameters, it does not throw any error. I am quite confused. I suspect the cloud lib version might have a bug in http request.

That's tricky. One possible reason could be that you are using a version of the library with a bug in your cloud environment and one version of the library without the bug locally. Are your versions locked using dependency management?

**Comment by everdance** [comment]
ok, so my cloud lib version is `3.3.1` while my local version is `3.0.0`

**Comment by bhelx** [comment]
@everdance interesting. If you change your local version to 3.3.1, are you able to reproduce locally? It seems possible a regression bug has been introduced.

**Comment by everdance** [comment]
I tried to reproduce it with 3.3.1 with single case, but couldn't. then suspecting rate limit, as our cloud environment has huge amount of records to process, I changed the script to run in true loop, it throws the same error after rate limit hit with both versions. 
```
while True:
      try:
            client.get_subscription('uuid-'+uuid)
   ....
```

**Comment by bhelx** [comment]
@everdance Thanks for getting down the root cause. I appreciate your patience. I see the problem here. It's twofold:

1. An error class is not present for rate limiting.
2. There should be a sensible fallback even when an error class is not present.

I'll open some tickets to fix both problems. I'll likely start with the second problem as it has broader impact.
