### ISSUE TITLE
Automated Exports API is missing in v3

### ISSUE THREAD

**Issue by michael-yin** [recurly/recurly-client-python#349]
I just noticed that the `Automated Exports API` merged in v2 is missing in v3. 

Here is the PR https://github.com/recurly/recurly-client-python/pull/288

I can still keep using v2 but I really appreciate that if you can fix it and I am happy to upgrade in a bit. 

Thx.

**Comment by bhelx** [comment]
It's not yet supported in V3. I will leave this open and report news back here, but we are working with our data team to get something supported in V3 with regards to exports.

**Comment by douglasmiller** [comment]
@michael-yin support for the Automated Exports API was recently added to v3 in the [3.12.0 release](https://github.com/recurly/recurly-client-python/blob/master/CHANGELOG.md#3120-2020-09-22)!
