### ISSUE TITLE
Error on request: TypeError: can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by zhavir** [recurly/recurly-client-python#358]
**Describe the bug**
The error occurs on failed connection between backend and recurly.

**To Reproduce**
It is randomly raised during requests

**Expected behavior**

Expecting to raise ApiError
here is the error recurly.base_client.BaseClient._make_request on
`
                    raise ApiError(
                        "Unknown Error. Recurly Request Id: " + resp.request_id, None)
`
- Which version of this library are you using?  recurly 3.4 
- Which version of the language are you using? python 3.7

**Comment by bhelx** [comment]
@zhavir it seems to me that we have not handled the case in which we were not issued a request id from the server. I've opened #359 to address it.

**Comment by bhelx** [comment]
@zhavir thanks for the detailed issue!

**Comment by zhavir** [comment]
@bhelx Thanks for the reply! Just an information, when will be released the next version of the SDK? 

btw nice profile pic!
