### ISSUE TITLE
Error trying to cast error response

### ISSUE THREAD

**Issue by romeroadrian** [recurly/recurly-client-python#369]
**Describe the bug**

Seems there is an error while trying to cast an error response due to a missing error class.

**To Reproduce**

I'm doing a preview request with a wrong zip code (we are using avalara here) and the raw response from the api is the following:

```
{"error":{"type":"service_not_available","message":"Tax service currently not available, please try again later."}}
```

The exception I'm having with the python client is the following:

```
  File ".../lib/python3.8/site-packages/recurly/client.py", line 2718, in preview_purchase
    return self._make_request("POST", path, body, None)
  File ".../lib/python3.8/site-packages/recurly/base_client.py", line 45, in _make_request
    raise Resource.cast_error(resp)
  File .../lib/python3.8/site-packages/recurly/resource.py", line 52, in cast_error
    return klass(
TypeError: 'NoneType' object is not callable
```

Seems code around https://github.com/recurly/recurly-client-python/blob/master/recurly/resource.py#L33 tries to build a class with the name `ServiceNotAvailableError` (matching the returned error type in the json response) but that doesn't exist.

**Expected behavior**

Error response is parsed and a `recurly.ApiError` is raised.

**Your Environment**

- Which version of this library are you using? 3.4.1
- Which version of the language are you using? 3.8

**Comment by bhelx** [comment]
Thanks for another highly detailed issue report @romeroadrian 

You're right, it should be falling back to ApiError if there is not a specific class.

Also i believe `service_not_available` might be the wrong error in this case. We have an existing ticket open for this problem. I'll push to see if we can get that fixed as well.

**Comment by romeroadrian** [comment]
@bhelx Right, `service_not_available` is really confusing here. Thanks!

**Comment by bhelx** [comment]
Apologies for the long turnaround, if you have a moment try #372

**Comment by romeroadrian** [comment]
@bhelx thanks! Working fine now. Do you plan a new release with this change?
