### ISSUE TITLE
Missing API call for listing account subscriptions

### ISSUE THREAD

**Issue by autronix** [recurly/recurly-client-python#384]
Current python v3 API library is missing a function for listing account subscriptions.

I managed to add it on my local environment in the `client.py` file:

```python
    def list_account_subscriptions(self, account_id):
        """List an account's subscriptions

        Parameters
        ----------
        account_id : str
            Account ID or code. For ID no prefix is used e.g. `e28zov4fw0v2`. For code use prefix `code-`, e.g. `code-bob`.

        Keyword Arguments
        =================
        
        Returns
        -------
        Pager
            A list of the account's subscriptions.
        """
        path = self._interpolate_path("/accounts/%s/subscriptions", account_id)
        return Pager(self, path, kwargs)
```

Used this in a quick project and seemed to work.

**Comment by douglasmiller** [comment]
Thank you for reporting this @autronix. Could you provide some information about what version of the client library you are using? The `list_account_subscriptions` method is been present in the v3 API client library since the [original beta release](https://github.com/recurly/recurly-client-python/blob/3.0b2/recurly/client.py#L792) and appears to still be present in the [current 3.4.2 release](https://github.com/recurly/recurly-client-python/blob/3.4.2/recurly/client.py#L801)

**Comment by autronix** [comment]
I followed the instructions for installing the recurly API library through pip. I ran `pip install recurly --upgrade`

Here is the version:
![image](https://user-images.githubusercontent.com/2739878/78821185-152d2180-79a7-11ea-874c-e99f68558eeb.png)

**Comment by douglasmiller** [comment]
Okay, well then you have the latest version, 3.4.2.

How did you initially discover that the method was missing from the client? Did your script throw an exception when trying to use it?

**Comment by autronix** [comment]
Yes and the documentation was missing the python definition for it:
![image](https://user-images.githubusercontent.com/2739878/78822474-1eb78900-79a9-11ea-9804-79d3c588c5bf.png)

 also, the autosuggest feature of the IDE was not showing any options associated with getting the list of subscriptions from the account.

**Comment by douglasmiller** [comment]
> the documentation was missing the python definition for it

There are a few places where we have gaps in our per-language examples. This operation is one of them, unfortunately. We already have an initiative to fill in these gaps, but I will make sure that `list_account_subscriptions` is included in the python gap list. Thank you for bringing this up, as the code examples are very useful for developers and we strive to make the developer portal as useful as possible.

That said, all of our v3 client libraries are automatically generated from the same openapi specification document. While there may not be code samples in the developer portal, then functionality is still present. 

You should be able to find a [complete list of operations and reference documentation](https://recurly-client-python.readthedocs.io/en/latest/) on the ReadTheDocs page.

> the autosuggest feature of the IDE was not showing any options associated with getting the list of subscriptions from the account

What IDE are you using and does the IDE show options for the other operations in the client?

**Comment by autronix** [comment]
Thank you.

I am using PyCharm Professional (Jetbrains), it did show all of the available options for the client object, but no list subscriptions for account was present; just to be clear though, when I opened the library files, after inspection, I was unable to find any reference to listing subscriptions for accounts in the `clients.py` file that was installed through the `pip install recurly --upgrade` command.

I had to manually create the function on the venv for the project I was working on in order to get that functionality working. Ultimately, it was both missing from the documentation and from the package that was delivered by pip.

Let me know if you need additional details.

**Comment by bhelx** [comment]
Seems pretty mysterious and I'm not sure what is happening here. I went ahead and checked both the source and i downloaded the release on `pypi` to verify it's there. I have a gut feeling that the `pip` command may be installing the library to a different location than what your program is using. Perhaps one thing you could try is see what version of the client is being loaded into your program. Try dropping this somewhere in your program:

```python
import recurly
print(recurly.__version__)
```

you should see something like `3.4.2` if you are using the latest library.

**Comment by autronix** [comment]
Actually, my apologies for the confusion, taking a closer look at the `client.py` that was installed, I can see that I had missed the `list_account_subscriptions` method there, right above `list_account_transactions`.

The documentation threw me off and in my rush to get script working, I didn't take the time to properly search the code when I was inspecting it for the account subscriptions.

To confirm, the version is 3.4.2, and the `list_account_subscriptions` function is indeed present, but for some reason wasn't picked up by the IDE.

Thanks for the help

**Comment by douglasmiller** [comment]
Happy to hear that you were able to get this sorted out. Let us know if you have any additional concerns.
