### ISSUE TITLE
Deprecation warning due to invalid escape sequences

### ISSUE THREAD

**Issue by tirkarthi** [recurly/recurly-client-python#391]
**Describe the bug**

Deprecation warning due to invalid escape sequences. Using raw strings or escaping them again helps in resolving this. Check https://github.com/asottile/pyupgrade/ for automatic fix of this.

**To Reproduce**

```
find . -iname '*.py' | grep -Ev 'rdf4|tool|doc' | xargs -P4 -I{} python3.8 -Wall -m py_compile {}
./tests/test_client.py:8: DeprecationWarning: invalid escape sequence \d
  self.assertRegex(client.api_version(), "v\d{4}-\d{2}-\d{2}")
```

**Your Environment**

- Which version of this library are you using? master branch
- Which version of the language are you using? Python 3.8

**Comment by bhelx** [comment]
@tirkarthi thanks for the clear report and the steps to fix. We will get this out in the next release.
