### ISSUE TITLE
Ability to set request timeout

### ISSUE THREAD

**Issue by benweatherman** [recurly/recurly-client-python#422]
I'd like to be able to configure a request timeout so that if the recurly API is taking awhile to respond, the client won't wait on a response that will never come.

It seems like that functionality has been available in the past, but it's hard to determine where these things got culled:
- https://github.com/recurly/recurly-client-python/pull/166/files
- https://github.com/recurly/recurly-client-python/issues/59 and https://github.com/recurly/recurly-client-python/blob/eec9266e8b5055598772aa7dae5eb4375558f360/CHANGELOG#L87
- https://github.com/recurly/recurly-client-python/issues/223#issuecomment-344719298

I was considering adding this functionality, but the contributing guidelines suggested I post here first.

I was going to tackle this issue by adding:
1. a default arg on `BaseClient.__init__` to allow passing a timeout
2. an environment var settable similar to `STRICT_MODE`

Thoughts on this approach? Any reason we _shouldn't_ add the ability to set a timeout?

**Comment by bhelx** [comment]
@benweatherman thanks for seeking advice! I agree with the option of adding it as a constructor option. In the next major version we can support overriding it on a request level (once this change makes it into the main branch https://github.com/recurly/recurly-client-python/pull/420). For the time being, it can be global to the client. Does that sound like what you were suggesting?

BTW, the changelog entry you provided is from version 2. So the feature was lost as a gap when we upgraded major versions.

**Comment by bhelx** [comment]
> Any reason we shouldn't add the ability to set a timeout?

FWIW, it's a task that we had backlogged. We *do* agree that it's important. We'll provide some documentation explaining why you may want to change it.

**Comment by benweatherman** [comment]
Yes, that sounds great! For our needs, overriding globally on the client is all we need (we don't have a need currently to set timeout per request).

Thanks for the insight!

**Comment by bhelx** [comment]
Cool, our team can follow up with that option later. Then both will be supported.
