### ISSUE TITLE
Unable to create plan add ons

### ISSUE THREAD

**Issue by mbeale** [recurly/recurly-client-python#43]
The XML does not seem to render properly.  The API is expecting the unit_amount_in_cents value to be encased in a currency tag.  

Expecting this:

     <add_on>
       <add_on_code>ipaddresses</add_on_code>
       <name>Extra IP Addresses</name>
       <unit_amount_in_cents>
          <USD>200</USD>
       </unit_amount_in_cents>
     </add_on>

But lib is sending this:

     <add_on>
       <add_on_code>ipaddresses</add_on_code>
       <name>Extra IP Addresses</name>
       <unit_amount_in_cents>200</unit_amount_in_cents>
     </add_on>

**Comment by bhelx** [comment]
@mbeale This shouldn't be an issue anymore. Please re-open if you are still having problems with this.
