### ISSUE TITLE
Client timeout keyword parameter has been (mistakenly) removed in v4.0.0

### ISSUE THREAD

**Issue by cederberg** [recurly/recurly-client-python#478]
The `timeout` keyword parameter has been removed from `recurly.Client.__init__(...)` in v4.0.0.

Its removal isn't mentioned in the release notes, nor in the detailed change log. I assume that it has been removed due to a mistake in tagging, branching or such.

Here are the original release notes for v3.15.0 clearly mentioning it:
https://github.com/recurly/recurly-client-python/releases/tag/3.15.0
https://github.com/recurly/recurly-client-python/pull/423

**Comment by douglasmiller** [comment]
@cederberg, thank you for bringing this to our attention. There were a couple of updates that some how didn't get included. This will be fixed with https://github.com/recurly/recurly-client-python/pull/479

**Comment by douglasmiller** [comment]
@cederberg This update was included in the `4.0.1` (and following) release. Please don't hesitate to reach out with any additional issues that you encounter.
