### ISSUE TITLE
Invoices does not have coupon code

### ISSUE THREAD

**Issue by DawerRafi** [recurly/recurly-client-python#492]
The Invoice object does not contain coupon information, even though coupon_code is available in Invoices Export in Recurly.

Reference: https://recurly-client-python.readthedocs.io/en/latest/recurly.html?highlight=clientpy#recurly.resources.Invoice

But here in [Recurly docs](https://docs.recurly.com/docs/invoices-exports), we have coupon_code present in Invoices - Summary and even in the old deprecated Invoices export

Using recurly==3.12.0
Python 3.7.3

**Comment by joannasese** [comment]
Hi @DawerRafi. Thanks for reporting. We will take a look and get back to you ASAP.

**Comment by joannasese** [comment]
Hi @DawerRafi. Apologies for the delay here. Invoices are not currently designed to contain coupon information. The API is not a 1-1 match of our data exports, so `coupon_code` may be available in an invoice export but not included in an API response. I hope that clears things up. I'll close this issue but if you have any questions, please feel free to write back.

**Comment by DawerRafi** [comment]
Hi @joannasese, thanks for your reply. Its fine if the API is not a 1-1 match. However, I would hope the API would be able to give additional information if needed through the exports. 

I have a related problem, where I want to get additional Invoice information from the API by looping over records from the Automated Export, but in the Automated Export for Invoices, we have UUID, instead of internal ID which I cannot use in get_invoice() function. Can we handle UUID's for Invoices too, like we do for get_subscription() and other calls? Because without this, the Automated Exports are more or less useless.
