### ISSUE TITLE
Handling Embedded objects

### ISSUE THREAD

**Issue by mbeale** [recurly/recurly-client-python#50]
The python library does not handle embedded objects well.  For instance the add_ons need to be fully replaced in order to update them.   Example:

newaddon = SubscriptionAddOn()
newaddon.add_on_code = 'my-new-add-on'
newaddon.quantity = 2
add_ons = subscription.subscription_add_ons
# need to copy old add-ons

subscription.subscription_add_ons = []
for a in add_ons:
    tempaddon = SubscriptionAddOn()
    tempaddon.add_on_code = a.add_on_code
    tempaddon.quantity = a.quantity
    tempaddon.unit_amount_in_cents = a.unit_amount_in_cents
    subscription.subscription_add_ons.append(tempaddon)
# append new add-on

subscription.subscription_add_ons.append(newaddon)
# 
# Adjust the quantity of one add-on
# 
# need to copy old add-ons

add_ons = subscription.subscription_add_ons
subscription.subscription_add_ons = []
for a in add_ons:
    tempaddon = SubscriptionAddOn()
    tempaddon.add_on_code = a.add_on_code
    tempaddon.quantity = a.quantity
    #check for a specific add-on
    if tempaddon.add_on_code == 'my-new-add-on':
        tempaddon.quantity = 6
    tempaddon.unit_amount_in_cents = a.unit_amount_in_cents
    subscription.subscription_add_ons.append(tempaddon)
# 
# Remove one add-on
# 

add_ons = subscription.subscription_add_ons
subscription.subscription_add_ons = []
for a in add_ons:
    if a.add_on_code != 'my-new-add-on':
        tempaddon = SubscriptionAddOn()
        tempaddon.add_on_code = a.add_on_code
        tempaddon.quantity = a.quantity
        tempaddon.unit_amount_in_cents = a.unit_amount_in_cents
        subscription.subscription_add_ons.append(tempaddon)

**Comment by aaron-suarez** [comment]
This is a design issue that will not be able to be fixed in this major version of the library.
