### ISSUE TITLE
How to convert a resource to a json object?

### ISSUE THREAD

**Issue by tcsullens** [recurly/recurly-client-python#668]
Duplicate of https://github.com/recurly/recurly-client-python/issues/629, but that was closed with no resolution — is there idiomatic way to convert a Resource into a valid json object? Is this not an expected use-case?

**Comment by douglasmiller** [comment]
Hey @tcsullens,

For non-pager responses, it is possible to access the raw response body. However, it's primary purpose is more for debugging purposes than standard functionality. What is your use case where you need the JSON object?

```python
account = client.get_account(account_id)
res = account.get_response()
print("Account JSON: %s" % json.dumps(res.body))
```

**Comment by tcsullens** [comment]
>For non-pager responses, it is possible to access the raw response body. 

Ah, thanks for that!

>However, it's primary purpose is more for debugging purposes than standard functionality. What is your use case where you need the JSON object?

Interesting, in our case we want to serialize these resources to JSON that we can write to files/storage for a data ingestion process. We ended up just using python's `requests` and interacting with the Recurly API directly, but were curious if we were missing something in the documentation/source. 
Maybe ours is more an unusual use-case? I'm happy to close this as resolved at this point!
