### ISSUE TITLE
Return resume_at field when retrieving subscriptions

### ISSUE THREAD

**Issue by enberg** [recurly/recurly-client-python#685]
Currently the client doesn't return the resume_at field when retrieving subscriptions.

The field exists and is returned from the API but the python client omits it.

**Comment by douglasmiller** [comment]
@enberg, could you please clarify which version of the python client you are using?

**Comment by enberg** [comment]
Hey @douglasmiller!

Currently on `recurly = "==4.40.0" `

**Comment by douglasmiller** [comment]
@enberg, I manually checked raw API responses (using curl) for subscriptions and I don't see a `resume_at` property being returned. I also looked through the code that renders the API response and there is no `resume_at` property being rendered.

The only place that I see `resume_at` documented anywhere is in our [XML webhooks](https://recurly.com/developers/reference/webhooks/#paused-subscription). Are you attempting to use the JSON python client to parse the XML payloads?

**Comment by enberg** [comment]
Probably a miss on our end, mixing up webhook xml response with the API, sorry for the confusion.

So then the actual request would be to get the `resume_at` field through the API, but that would be somewhere else, I'll try to find the correct forum for that request.
